### ISSUE TITLE
DeprecationWarning: "@coroutine" decorator is deprecated

### ISSUE THREAD

**Issue by ylassoued** [Martiusweb/asynctest#161]
Module mock.py, function `proxy`, declared in line 599, uses decorator `@asyncio.coroutine`.
It seems that the asyncio `@coroutine` decorator is **deprecated since Python 3.8**.
Please use `async def` instead.
Source code should be modified to look something like:
```
           async def proxy():
            try:
                if inspect.isawaitable(result):
                    return (yield from result)
                else:
                    return result
            finally:
                _mock_self.await_count += 1
                _mock_self.await_args = _call
                _mock_self.await_args_list.append(_call)
                yield from _mock_self.awaited._notify()
```

**Comment by RemiCardona** [comment]
Asynctest partially works on 3.8 but fails almost completely on 3.9, see https://github.com/Martiusweb/asynctest/issues/132 and https://github.com/Martiusweb/asynctest/issues/144. So it's much bigger than just the use of `@coroutine`.

**Comment by ylassoued** [comment]
Thanks @RemiCardona! Hmmm, this is really disappointing! Does this mean that I should just avoid using this API for Python 3.8 and above? Or is a new version, with full support for Python 3.8+, planned?

**Comment by WolfgangFahl** [comment]
In my case python 3.11 complains:
```File "/home/runner/work/justpy/justpy/tests/base_server_test.py", line 7, in <module>
    import asynctest
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/asynctest/__init__.py", line 22, in <module>
    from .case import *
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/asynctest/case.py", line 54, in <module>
    import asynctest.selector
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/asynctest/selector.py", line 29, in <module>
    from . import mock
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/asynctest/mock.py", line 428, in <module>
    class _AwaitEvent:
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/asynctest/mock.py", line 433, in _AwaitEvent
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```
